version: '3.8'
services:
  postgres:
    image: postgres:16.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mynewdatabase
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  goapp:
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:mysecretpassword@postgres:5432/mynewdatabase?sslmode=disable
    ports:
      - "8080:8080"
    command: >
      sh -c "./migrate.sh && ./myapp"

volumes:
  pgdata:
